services:

  web:
    build:
      context: ./ozguven_website/
    command: gunicorn ozguven_website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./ozguven_website/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose:
     - 8000
    env_file:
      - ./.env/dev.env

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles


volumes:
  staticfiles: